name: Compile SCSS to CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # You can specify the Node.js version you need

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Compile SCSS to CSS
      run: pnpm run dev

    - name: Upload CSS file
      uses: actions/upload-artifact@v2
      with:
        name: compiled-css
        path: dist/styles.css
